[build]
  publish = "/"  # Root directory where your files are located
  command = ""  # No build command needed for static site

# Global headers for all paths
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets for 1 hour, with revalidation
    Cache-Control = "public, max-age=3600, must-revalidate"
    # Required for service worker to work across different paths
    Service-Worker-Allowed = "/"

# Special handling for service worker file
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    # Important: Don't cache the service worker
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Handle SPA routing - redirect all 404s to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For preloading/prefetching resources
[[headers]]
  for = "/*.js"
  [headers.values]
    Link = "</service-worker.js>; rel=serviceworker; scope=/"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
